- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Robot/ITDbot.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Robot/Robot.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Robot/systems/MecanumDriveTrain.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/resourses/AdvancedGamepad.java
- build.dependencies.gradle
> copied core code from CS repo

- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Robot/ITDbot.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Robot/Robot.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/opmodes/GeneralOpMode.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/opmodes/MainTeleOp.java
- build.gradle
- gradle.properties
- gradle/wrapper/gradle-wrapper.properties
> Make Drive Train Work In Main TeleOp

- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/resourses/PIDController.java
Finished the PID Controller class. if you could do a quick code review before Saturday that would be super helpful, else it is ok.
fixes #14
> PID controller class complete

- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/opmodes/MainTeleOp.java
We created a variable for slow mode.
> Slow mode variable

- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Robot/ITDbot.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Robot/Robot.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/resourses/Odometry.java
Used to track where the robot is in space! we did some the IMU code from robot.java and into Odometry.java
yay :tada:
fixes #6
> Created odometry class

- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Robot/ITDbot.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Robot/Robot.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Robot/systems/MecanumDriveTrain.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/opmodes/GeneralOpMode.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/resourses/PathFollowing.java
created the path following class that 
fixes #7 
note that there will be some merge conflicts when merging pathFollowing and Angle correction in together. they should not be super hard and I can deal with it :)
> Path following complete

- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/resourses/InverseKinematics.java
> Inverse kinematics complete

- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/OpModes/AprilTagTest.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/OpModes/GeneralOpMode.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Resources/AprilTagSystem.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Robot/ITDbot.java
Tested and it works! 
fixes #28
> April tags Finished!

- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/OpModes/ArmTest.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Resources/InverseKinematics.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Robot/Systems/SpampleArm.java
just syncing things so we don't run into major issues later on with git :)
> Sync Teleop changes with testing branch - not major changes so should not need code review

- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/OpModes/ArmTest.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/OpModes/BlueLeftAutoAxolotl.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/OpModes/BlueRightAutoAxolotl.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/OpModes/GeneralOpMode.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/OpModes/RedLeftAutoAxolotl.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/OpModes/RedRightAutoAxolotl.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Resources/InverseKinematics.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Resources/Utlities.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Robot/Autonomous/AutonomousFunctions.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Robot/ITDbot.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Robot/Systems/SpampleArm.java
sync auto with current progress, going to open a new auto branch after the sync is complete.
this branch is full of pseudocode for autonomous routes by Andrea.
> Autonomous sync

- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/OpModes/ArmTest.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/OpModes/GeneralOpMode.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/OpModes/MainTeleOp.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Resources/AprilTagSystem.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Resources/InverseKinematics.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Resources/OdometryOTOS.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Resources/TwoWheelOdometry.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Robot/ITDbot.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Robot/Robot.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Robot/Systems/Claw.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Robot/Systems/SpampleArm.java
we have done a lot of changes in the arm testing branch related to all works of the robot systems, this process probably should have been done over several branches but we kind of just through it all into this branch over the span on integration week.
> Arm testing tada 

- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/OpModes/MainTeleOp.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Resources/InverseKinematics.java
- build.gradle
We refactored inverse kinematics to make it more easily readable and used math functions instead of custom. We also fixed some bugs. Needs testing.
> Refactored Inverse Kinematics

- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/OpModes/MainTeleOp.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Robot/Systems/SpampleArm.java
> Tele op twist control

- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Resources/InverseKinematics.java
Refactored a variable to make it easier to understand.
> Refactored ELBOW_LENGTH to FOREARM_LENGTH

- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/OpModes/MainTeleOp.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/OpModes/climberTest.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Robot/Robot.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Robot/Systems/Climber.java
> Climber for dec14th

- FtcRobotController/src/main/java/org/firstinspires/ftc/robotcontroller/external/samples/SensorSparkFunOTOS.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/OpModes/BaseAuto.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/OpModes/RedLeftAutoAxolotl.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/OpModes/RedRightAutoAxolotl.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/OpModes/TestAuto.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Resources/OdometryOTOS.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Resources/PathFollowing.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Resources/Utlities.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Robot/Autonomous/AutonomousFunctions.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Robot/Systems/MecanumDriveTrain.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Robot/Systems/SpampleArm.java
> Autonomous axolotl

- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/OpModes/MainTeleOp.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Robot/Robot.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Robot/Systems/Climber.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Robot/Systems/SpampleArm.java
> Ps4 controllers integration

- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/OpModes/ArmTest.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/OpModes/MainTeleOp.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/OpModes/shoulderCalibration.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Robot/Systems/SpampleArm.java
> Shoulder retuning

- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/OpModes/BaseAuto.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/OpModes/RedLeftAutoAxolotl.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/OpModes/RedLeftAutoBarnacle.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/OpModes/RedRightAutoAxolotl.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/OpModes/TestAuto.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Resources/PathFollowing.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Robot/ITDbot.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Robot/Robot.java
We made a new function for setting the speed within robot (setRobotSpeed) combining several other functions. We moved constants from BaseAuto to Robot so that it would be better encapsulated and made them final, private and all caps to fit the style guide.
> Path Following Code Cleanup

- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/OpModes/AprilTagTest.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/OpModes/ArmTest.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/OpModes/BaseAuto.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/OpModes/DemoTeleOp.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/OpModes/GeneralOpMode.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/OpModes/MainTeleOp.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/OpModes/RedLeftAutoAxolotl.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/OpModes/RedLeftAutoBarnacle.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/OpModes/RedRightAutoAxolotl.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/OpModes/TestAuto.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/OpModes/climberTest.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/OpModes/shoulderCalibration.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Resources/OdometryOTOS.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Robot/Autonomous/AutonomousFunctions.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Robot/ITDbot.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Robot/Robot.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Robot/Systems/SpampleArm.java
> Auto barnacle and Jan 18th changes

- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/OpModes/MainTeleOp.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/OpModes/climberTest.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Robot/ITDbot.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Robot/Robot.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Robot/Systems/Climber.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Robot/Systems/SpampleArm.java
> Actual climber!!!

- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/OpModes/AprilTagTest.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/OpModes/ArmTest.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/OpModes/CompetitionTeleop.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/OpModes/ElbowServoCalibration.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/OpModes/MainTeleOp.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/OpModes/SampleDetectionTesting.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/OpModes/TestAuto.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/OpModes/climberTest.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/OpModes/shoulderCalibration.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Resources/InverseKinematics.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Resources/SampleDetectionPipeline.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Resources/SampleDetectionProcessor.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Robot/Systems/SampleCamera.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Robot/Systems/SpampleArm.java
> Vision in to teleop
